### ISSUE TITLE
Can we use this model in autoregressive mode? 

### ISSUE THREAD

**Issue by d5555** [Aroksak/RSE#1]
Can we train and use this model in autoregressive mode (when we feed it with tokens one by one) ?

**Comment by Aroksak** [comment]
Hello!

This model operates on the whole sequence at once, so no, it can not be used in autoregressive mode as is.

However, since one model can operate on sequences of any length (with padding to powers of 2), you can simulate autoregressive mode by providing it with longer and longer segments of one sequence.

**Comment by d5555** [comment]
Excellet ! Thanks for sharing the code!
